config/routes.rb
Rails.application.routes.draw do

  resources :charges, only: [:new, :create] do
    post '/cancel_subscription' => 'charges#cancel_subscription', as: :cancel_subscription
  end

  resources :wikis do
    post '/add_collaborator' => 'wikis#add_collaborator', as: :add_collaborator
    post '/remove_collaborator' => 'wikis#remove_collaborator', as: :remove_collaborator
  end

  devise_for :users

  resources :users, only: [:show]

  get 'about' => 'welcome#about'

  root 'welcome#index'

end

app/models/collaboration.rb
class Collaboration < ActiveRecord::Base
  belongs_to :user
  belongs_to :wiki
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  extend FriendlyId
  friendly_id :name, use: [:slugged, :finders]

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :lockable


  has_many :created_wikis, class_name: "Wiki", foreign_key: "user_id"
  has_many :collaborations
  has_many :collaborating_wikis, through: :collaborations, source: :wiki

  enum role: [:standard, :premium, :admin]
  after_initialize(:set_default_role, {if: :new_record?})

  def set_default_role
    self.role ||= :standard
  end

  def change_user_role(new_role)
    update_attribute(:role, new_role)
  end

  def save_subscription(sub)
    update_attribute(:subscription, sub)
  end

  def delete_subscription
    update_attribute(:subscription, nil)
  end

  def cancel_privates
    self.created_wikis.each { |wiki| puts wiki.set_as_public }
  end

  def avatar_url(size)
    gravatar_id = Digest::MD5::hexdigest(self.email).downcase
    "http://gravatar.com/avatar/#{gravatar_id}.png?s=#{size}"
  end

  def downgrade
    self.delete_subscription
    self.change_user_role(0)
    self.cancel_privates
  end

end

app/models/wiki.rb
class Wiki < ActiveRecord::Base

  extend FriendlyId
  friendly_id :title, use: [:slugged, :finders]

  belongs_to :user
  has_many :collaborations
  has_many :collaborators, through: :collaborations, source: :user

  after_initialize(:set_default_private, {if: :new_record?})

  validates :title, length: {minimum: 2}, presence: true
  validates :body, length: {minimum: 10}, presence: true
  validates :user, presence: true
  validates :slug, presence: true

  scope :visible_to, -> (user){user ? where("private is null or private=? or user_id=?",false, user.id).uniq : where(private:false)}
  scope :public_wikis, -> {where(private:false)}
  scope :private_wikis, -> {where(private:true)}
  scope :my_wikis, -> (user){where(user_id:user)}
  default_scope {order('lower(title)')}

  def set_default_private
    self.private ||= false
  end

  def set_as_public
    update_attribute(:private, false)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Pundit

  before_action :configure_permitted_parameters, if: :devise_controller?

  before_action :authenticate_user!

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized


  protect_from_forgery with: :exception


private
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end
  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(request.referrer || root_path)
  end

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def new
      @stripe_btn_data = {
        key: "#{Rails.configuration.stripe[:publishable_key]}",
        description: "Flaxipedia Membership for #{current_user.name}",
        plan: 'premium'
      }
  end

  def create
    @user = current_user
    customer = Stripe::Customer.create(
      email: current_user.email,
      source: params[:stripeToken]
    )

    charge = Stripe::Subscription.create(
      customer: customer.id,
      plan: 'premium',
    )
    @user.save_subscription(charge.id)
    @user.change_user_role(1)
    flash[:notice] = "#{current_user.name}, Your membership has been upgraded to premium!"
    redirect_to user_path(current_user)

  rescue Stripe::CardError => e
    flash[:alert] = e.message
    redirect_to new_charge_path
  end

  def cancel_subscription
    @user = current_user
    sub = Stripe::Subscription.retrieve(@user.subscription)
    sub.delete
    @user.downgrade
    flash[:notice] = "#{current_user.name}, Your premium membership has been cancled."
    redirect_to user_path(current_user)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    authorize @user
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  skip_before_action :configure_permitted_parameters

  skip_before_action :authenticate_user!


  def index
  end

  def about
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController

  skip_before_action :configure_permitted_parameters
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @wikis = policy_scope(Wiki)
  # @wikis = (Wiki.private_wikis.my_wikis(current_user)+Wiki.public_wikis).sort
  end

  def show
    @wiki = Wiki.find(params[:id])
  end

  def new
    @wiki = Wiki.new
  end

  def create
    @wiki = Wiki.new(wiki_params)
    @wiki.user = current_user

    if @wiki.save
      flash[:notice] = "Wiki successfully created"
      redirect_to [@wiki]
    else
      flash.now[:alert] = "There was an error, wiki not created"
      render :new
    end
  end

  def edit
    @wiki = Wiki.find(params[:id])
    authorize @wiki
  end

  def update
    @wiki = Wiki.find(params[:id])
    authorize @wiki
    @wiki.assign_attributes(wiki_params)

    if @wiki.save
      flash[:notice] = "Wiki successfully updated"
      redirect_to [@wiki]
    else
      flash.now[:alert] = "There was an error, wiki not updated"
      render :new
    end
  end

  def destroy
    @wiki = Wiki.find(params[:id])

    if @wiki.destroy
      flash[:notice] = "Wiki successfully deleted"
      redirect_to action: :index
    else
      flash.now[:alert] = "An error occured when attempting to delete wiki"
      render :show
    end
  end

  def add_collaborator
    @wiki = Wiki.find(params[:wiki_id])
    @user = User.find(params[:user_id])
    @wiki.collaborators << @user
    redirect_to @wiki
  end

  def remove_collaborator
    @wiki = Wiki.find(params[:wiki_id])
    @user = User.find(params[:user_id])
    @wiki.collaborations.find_by(user_id: @user.id).delete
    redirect_to @wiki
  end

  private
    def wiki_params
      params.require(:wiki).permit(:title, :body, :private)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    options = {
      :autolink => true,
      :space_after_headers => true,
      :no_intra_emphasis => true
    }
    markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, options)
    markdown.render(text).html_safe
  end
end

app/helpers/charages_helper.rb
module CharagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <h4>Click the button to Upgrade to Premium!</h4>
  <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount=<%= @stripe_btn_data[:plan] %> data-description="<%= @stripe_btn_data[:description] %>" ></script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Flaxipedia</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <ul class="nav nav-tabs">
      <li><%= link_to "Flaxipedia", root_path %></li>
      <li><%= link_to "About", about_path%></li>
      <li><%= link_to "Wikis", wikis_path%></li>
      <div class="pull-right user-info">
        <% if user_signed_in? %>
          Signed in as: <strong><%= current_user.name %></strong> <br>
          <div class="gravatar pull-left">
            <%= link_to image_tag(current_user.avatar_url(48), class: "gravatar"), "https://en.gravatar.com/" %>
          </div>
          <div class="pull-right">
          <%= link_to 'Profile', user_path(current_user), :class => 'navbar-link' %> <br> <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
          </div>
        <% else %>
          <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> <br>
          <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
        <% end %>
      </div>
    </ul>
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>">
        <%= value %>
      </div>
    <% end %>


<%= yield %>
</div>
</body>
</html>

app/views/users/show.html.erb
<br>
<div class="jumbotron user-profile">
  <div class="user-image-div">
    <%= link_to image_tag(@user.avatar_url(128), class:"user-image"), 'https://en.gravatar.com/' %>
  </div>
  <div class="user-info-div">
    <h2><%=@user.name%></h2>
    <h4>Email: <%=@user.email%></h4>
    <h4>Membership Type: <%=@user.role%></h4>
  </div>
  <div class="buttons">
    <% if @user == current_user %>
      <%= link_to 'Edit profile', edit_user_registration_path, :class => 'btn btn-success' %>
      <% if @user.standard? %>
        <%= link_to 'Upgrade Membership', new_charge_path, class: 'btn btn-primary'%>
      <% elsif @user.premium? %>
        <%= link_to 'Cancel Premium Membership', charge_cancel_subscription_path(@user), class: 'btn btn-default', method: :post, data: {confirm: "Canceling your subscription will cause all of your private wikis to become public, are you sure you want to cancel?"}%>
      <%end%>
    <%end%>
  </div>
</div>

app/views/welcome/about.html.erb
<h1>Welcome to Flaxipedia</h1>
<p>Flaxipedia is being created by Devon Henegar with his Bloc mentor as part of a project designed to help him learn Ruby on Rails, the project is commonly known as blocipedia</p>

app/views/welcome/index.html.erb
<div class="jumbotron page-header">
  <h1>Flaxipedia</h1>
  <p>Flaxipdedia is the place to come for information on the world of Flax as authored by D.M. Henegar</p>
  <p><%= link_to 'Register', new_user_registration_path, class: 'btn btn-primary btn-lg' %></p>
</div>

app/views/wikis/_form.html.haml
= form_for [wiki] do |f|
  -if wiki.errors.any?
    %div.alert.alert-danger
      %h4
        = pluralize(wiki.errors.count, "error")
      %ul
        -wiki.errors.full_messages.each do |msg|
          %li
            =msg
  %div.form-group
    = f.label :title
    = f.text_field :title, class: "form-control",  autofocus: true, placeholder: "Enter Wiki Name"
  %div.form-group
    = f.label :body
    = f.text_area :body, rows: 12, class: "form-control", placeholder: "Enter Wiki Info"
  -if current_user.admin? || current_user.premium?
    %div.form-group
      = f.label :private, class: 'checkbox' do
        = f.check_box :private
        Private wiki
  %div.form-group
    = f.submit "Save", class: 'btn btn-success'

app/views/wikis/edit.html.haml
%h1 Edit Wiki
= render partial: 'form', locals:{wiki: @wiki}

- if @wiki.private? && (@wiki.user_id == current_user.id)
  %button.btn.btn-primary{:type => "button", :data => {:toggle => "modal", :target => "#collaborators_modal"}} Collaborators



%div#collaborators_modal.modal
  %div.modal-content
    %div.modal-body
      - User.all.each do |u|
        -if u.id != current_user.id
          %div
            - if @wiki.collaborators.include?(u)
              = "#{u.name}(#{u.id})"
              = link_to "remove as collaborator", wiki_remove_collaborator_path(@wiki, user_id: u.id), class: 'btn btn-danger', method: :post
            - else
              = "#{u.name}(#{u.id})"
              = link_to "add as collaborator", wiki_add_collaborator_path(@wiki, user_id:u.id), class: 'btn btn-primary', method: :post
    %div.modal-footer
      %button.btn.btn-secondary{ :type => 'button', :data => {:dismiss => "modal"}} Close

app/views/wikis/index.html.haml
%h1
  All Wikis:
%div.row
  %div.col-md-8
    - @wikis.each do |wiki|
      %div.media
        %div.media-body
          %h4.media-heading
            %p
              = link_to wiki.title, wiki
  %br
    - if current_user
      %div.col-md-8
        = link_to "New Wiki", new_wiki_path, class: "btn btn-success pull-right"

app/views/wikis/new.html.haml
%h1
  New Wiki

=render partial: 'form', locals:{wiki: @wiki}

app/views/wikis/show.html.haml
%h1
  =@wiki.title

%p
  =markdown(@wiki.body)

- if current_user
  %div.col-md-4.pull-right
    = link_to "Edit", edit_wiki_path(@wiki), class: "btn btn-success"
    = link_to "Delete", [@wiki], method: :delete, class: "btn btn-danger", data: {confirm: "are you sure you want to delete this wiki?"}